version: '3.4'

services:
  dockerminiminalapis:
    image: ${DOCKER_REGISTRY-}dockerminiminalapis
    container_name: api
    build:
      context: .
      dockerfile: DockerMiniminalApis/Dockerfile
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=W3nc3s*1234
      - MSSQL_PID=Express
    volumes:
      - type: volume
        source: sql_data
        target: /var/opt/mssql
volumes:
  sql_data: 
